[target.thumbv6m-none-eabi]
#runner = 'arm-none-eabi-gdb'

runner = 'probe-rs run --chip=STM32F030F4Px'

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv6m-none-eabi"

[profile.release]
opt-level = "z"
